Creating a data model
olaishola05/blog pull request #3
Opened 2022-04-27 20:09 UTC by netman5

# Creating a data model

- Build project schema.
  - Create and run the migration for users, posts, comments, and likes files.
  - Table created and column names match the ERD diagram.
  - Foreign keys should be included.
  - All columns that are foreign keys have a corresponding index.

2022-04-27 20:21 UTC, bimbolabuari requested changes
Hi @netman5, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Create migration file for `users`, `posts` , `likes`, `comments` table

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 20:21 UTC, bimbolabuari commented on db/migrate/20220427191552_create_posts.rb
> +      t.integer :Likes_Counter
Kindly use `snake_case` as this is part of Ruby's best practice 👍 

![image](https://user-images.githubusercontent.com/66112760/165623594-7efe2bb8-be50-4abe-be82-9e4ca374cd52.png)

2022-04-27 20:21 UTC, bimbolabuari commented on db/migrate/20220427190212_create_users.rb
> +      t.string :Bio
Kindly use `snake_case` as this is part of Ruby's best practice 👍 

```
      t.string : name
      t.string : photo
      t.string : bio
```

Please check for other occurrences 👍

2022-04-28 07:36 UTC, Meltrust approved these changes
Hi @netman5,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for refactoring your table columns to snake case, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 10:25 UTC, merged