Views
olaishola05/blog pull request #5
Opened 2022-05-06 21:24 UTC by netman5

# Add views to the blog

- Implement the design from the wireframes design for the blog app
- Add view to display lists of users and number of posts on the home page
- Add a view for the individual user  with a display for recent posts
- Add a view to display all posts from a user
- Add a view to display a single post from a user
- Add minimal styling to all views

2022-05-06 22:37 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @netman5 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct GitHub Flow.
✅ Descriptive pull request.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 22:37 UTC, Cathella commented on app/controllers/users_controller.rb
> +  end
✅ Users controller #index action renders all users to it's corresponding Views index page 👍🏻

2022-05-06 22:37 UTC, Cathella commented on app/views/users/_user.html.erb
> +  </div>
✅  Displays `user.photo`, `user.name` and `user.posts_counter` 👍🏻

2022-05-06 22:37 UTC, Cathella commented on app/views/posts/_post.html.erb
> +    <span>Likes: <%= post.likes.size ||= 0 %></div></span>
- [ ] [REQUIRED] Kindly use the likes_counter -  `<small>Likes: <%= post.likes_counter || 0 %></small>`

2022-05-06 22:37 UTC, Cathella commented on app/views/users/show.html.erb
> +    <button type='button' class='all-post-btn'>See all posts</button>
- [ ] [REQUIRED] The button or link should redirect to all posts path. See the suggestions below

`<%= link_to 'See all Post', user_posts_path(@user) %>`

2022-05-06 22:37 UTC, Cathella commented on app/views/posts/_post.html.erb
> +    <span>Comments: <%= post.comments.size ||= 'No comments yet' %></span>,
- [ ] [REQUIRED] Kindly use the recent_comments method to to render 5 most recent comments

```ruby
<% post.recent_comments.each do |comment| %>
  <p><%= comment.author.name %>: <%= comment.text %></p> 
 <% end %>
```

2022-05-06 22:37 UTC, Cathella commented on app/views/posts/show.html.erb
> +                <span>Comments: <%= @post.comments.size ||= 'No comments yet' %></span>,
- [ ] Kindly use the comments_counter instead

2022-05-06 22:37 UTC, Cathella commented on app/views/posts/show.html.erb
> +                <span>Likes: <%= @post.likes.size ||= 0 %></span>
- [ ] Kindly use the likes _counter instead

2022-05-07 11:00 UTC, bimbolabuari approved these changes
Hi @netman5, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 11:17 UTC, merged